name: Terraform Apply or Destroy Infrastructure

on:
  # For manual trigger
  workflow_dispatch:
  
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        options:
          - apply
          - destroy

jobs:
  applyOrDestroyInfra:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id : '${{ secrets.AWS_ACCESS_KEY }}'
            aws-secret-access-key : '${{ secrets.AWS_SECRET_KEY }}'
            aws-region: us-east-1

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2

       - name: Initialize Terraform
         run: terraform init

       - name: Select any action
         run: echo "selected action=> ${{ github.event.inputs.action }}"

       - name: Apply or Destroy Infra
         run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          fi
